### ISSUE TITLE
[BUG] Organization ID in API Key name does not have effect

### ISSUE THREAD

**Issue by bundyfx** [coinbase/cdp-sdk-python#12]
Hi Team,

It appears the organization ID in the API Key name does not have an effect on successful authentication. I assume this should do some sort of organization validation.

Example, a Key Name with this allows for successful authentication -> organizations/**zebra**/apiKeys/{key_id}

**Comment by John-peterson-coinbase** [comment]
Thank you for flagging @bundyfx !

Our team is aware of the bug and working on it! This is not a security flaw at this time because the `{key_id}` is validated and ensures proper authentication.

Please let us know if you have any more feedback after using the SDK!
