### ISSUE TITLE
Issue: Invocation of External Payable Functions Fails to Process amount Properly

### ISSUE THREAD

**Issue by Arnab-Afk** [coinbase/cdp-sdk-python#61]
**Issue Description**
The `invoke_contract` function in the Coinbase SDK, located at [wallet.py#L423](https://github.com/coinbase/cdp-sdk-python/blob/018313a88e1e413e7a9f997e29f8eaf5a9d1e367/cdp/wallet.py#L423), is designed to interact with smart contracts. However, there are two key issues related to its behavior and documentation:

1. **Invocation Issues with External Payable Functions:**
When invoking external payable functions, the `amount` parameter does not work as expected. Even when explicitly specified (and not passed within the `args`), the invocation fails, as the contract interaction does not properly handle the `value` field required for the payable function.
2. **Documentation Gap:**
The SDK's documentation for invoking arbitrary smart contracts, which provides an example of using `invoke_contract` with an explicitly provided ABI, does not mention the `amount` field at all. This omission leads to unawareness about the field's existence and usage, potentially causing confusion for developers implementing payable contract interactions.

**Expected Behavior**

- Invocation Behavior: The `amount` parameter should correctly map to the `value` field required for payable functions.

- Documentation: The `amount` parameter should be clearly documented in examples and guidelines for invoking arbitrary smart contracts.

**Actual Behavior**

- Invocation Issue: Payable functions invoked via `invoke_contract` fail to process the `amount` parameter provided through the function.

- Documentation Gap: No mention of the `amount` parameter in the documentation for invoking arbitrary smart contracts.

**Suggested Fixes**
- **Code Update:** Ensure the `amount` parameter is correctly translated to the value field during the invocation of payable functions.
- **Documentation Update:** 
  - Update the documentation to explicitly mention the `amount` field and its purpose.
  - Provide a clear example demonstrating how to use **invoke_contract** for payable functions, including the **amount** parameter.
  - Add more examples based on smart contract interactions specifically Invoking an arbitrary smart contracts.

**Relevant Code Reference**
- Invocation behavior: [wallet.py#L423](https://github.com/coinbase/cdp-sdk-python/blob/018313a88e1e413e7a9f997e29f8eaf5a9d1e367/cdp/wallet.py#L423).

**Comment by John-peterson-coinbase** [comment]
This is resolved with better error handling in https://github.com/coinbase/cdp-sdk-python/releases/tag/0.12.1
